export type CatalogSeedItem = {
  name: string;
  description: string;
  category: "entradas" | "pratos_principais" | "sobremesas" | "bebidas" | "vinhos";
  priceCents: number;
};

const entries: Array<[string, string, number]> = [
  ["Bruschetta da Casa", "Pão rústico, tomate confitado, manjericão e azeite", 2490],
  ["Carpaccio Clássico", "Lâminas de mignon, parmesão e molho de alcaparras", 3890],
  ["Ceviche Cítrico", "Peixe branco, leite de tigre, manga e coentro", 3690],
  ["Croquete de Costela", "Costela cozida lentamente com maionese de pimenta", 3290],
  ["Dadinho de Tapioca", "Queijo coalho, tapioca e geleia de pimenta", 2290],
  ["Bolinho de Bacalhau", "Bacalhau desfiado, batata e ervas frescas", 2890],
  ["Coxinha de Pato", "Massa artesanal e recheio cremoso de pato", 3490],
  ["Queijo Brie Assado", "Mel, amêndoas tostadas e focaccia", 4190],
  ["Burrata Cremosa", "Tomates assados, pesto e pão de fermentação natural", 4290],
  ["Tartar de Salmão", "Salmão fresco, avocado, gergelim e cítricos", 4490],
  ["Tartar de Mignon", "Mignon picado na ponta da faca e batata crocante", 4390],
  ["Polvo à Provençal", "Polvo grelhado, batatas e azeite de ervas", 4890],
  ["Camarão Crocante", "Camarões empanados, aioli de limão e páprica", 4690],
  ["Lula à Dorê", "Anéis de lula dourados com molho tártaro", 3990],
  ["Mandioca Frita", "Mandioca crocante com manteiga de garrafa", 1890],
  ["Batata Rústica", "Batatas assadas, alecrim e aioli defumado", 2090],
  ["Focaccia de Alecrim", "Pão artesanal, azeite extravirgem e flor de sal", 1690],
  ["Azeitonas Marinadas", "Mix de azeitonas, laranja e ervas", 1790],
  ["Mix de Castanhas", "Castanhas brasileiras temperadas e tostadas", 1590],
  ["Homus com Pita", "Pasta de grão-de-bico, zaatar e pão sírio", 2490],
  ["Berinjela Defumada", "Babaganoush, romã e torradas", 2690],
  ["Mini Pastéis de Queijo", "Queijo meia cura e molho de pimenta doce", 2290],
  ["Escondidinho de Cogumelos", "Cogumelos frescos, purê de mandioquinha e queijo", 3190],
  ["Provolone à Milanesa", "Provolone empanado, mel picante e limão", 2990],
  ["Chips de Batata-doce", "Chips finos com dip de ervas", 1490],
  ["Salada Caprese", "Tomate, muçarela de búfala, pesto e balsâmico", 2790],
  ["Salada Caesar", "Alface romana, frango, parmesão e croutons", 3390],
  ["Salada Mediterrânea", "Folhas, grão-de-bico, feta e azeitonas", 3190],
  ["Vinagrete de Polvo", "Polvo, pimentões, cebola roxa e coentro", 4590],
  ["Tábua de Frios", "Queijos, charcutaria, frutas e pães artesanais", 5790],
];

const mains: Array<[string, string, number]> = [
  ["Filé Mignon ao Molho Rôti", "Mignon grelhado, batata gratinada e molho rôti", 7290],
  ["Medalhão ao Vinho Tinto", "Medalhões de mignon, risoto de parmesão e demi-glace", 7690],
  ["Entrecôte com Fritas", "Corte premium, batatas rústicas e manteiga de ervas", 6890],
  ["Costela Braseada", "Costela bovina, polenta cremosa e molho da cocção", 6490],
  ["Cordeiro Mediterrâneo", "Carré de cordeiro, cuscuz marroquino e hortelã", 7890],
  ["Frango Supreme", "Peito de frango recheado, arroz de amêndoas e jus", 4890],
  ["Confit de Pato", "Coxa de pato, purê de batata e frutas vermelhas", 6990],
  ["Salmão na Crosta", "Salmão, crosta de castanhas, legumes e molho cítrico", 6790],
  ["Bacalhau à Lagareiro", "Lombo de bacalhau, batatas ao murro e azeitonas", 7490],
  ["Polvo Grelhado", "Polvo na brasa, arroz negro e tomate confitado", 7690],
  ["Camarão ao Curry", "Camarões, arroz jasmim, leite de coco e coentro", 6690],
  ["Tilápia Crocante", "Filé de tilápia, purê de mandioquinha e saladinha", 4690],
  ["Risoto de Cogumelos", "Arroz arbóreo, cogumelos frescos e parmesão", 4790],
  ["Risoto de Limão Siciliano", "Risoto cremoso, limão siciliano e queijo grana", 4590],
  ["Nhoque de Mandioquinha", "Nhoque artesanal, fonduta de queijo e sálvia", 4490],
  ["Ravioli de Ricota", "Ravioli fresco, espinafre e manteiga de ervas", 4690],
  ["Lasanha da Nonna", "Lasanha de ragu bovino, bechamel e parmesão", 4890],
  ["Spaghetti ao Pomodoro", "Massa italiana, tomates frescos, manjericão e grana", 3990],
  ["Fettuccine Alfredo", "Massa fresca, parmesão, creme e frango grelhado", 4690],
  ["Penne ao Funghi", "Penne, mix de cogumelos e creme de parmesão", 4490],
  ["Hambúrguer Sabor & Mesa", "Blend artesanal, queijo, bacon, cebola e fritas", 4290],
  ["Burger Vegetariano", "Hambúrguer de grão-de-bico, queijo e fritas", 3890],
  ["Parmegiana de Mignon", "Mignon empanado, molho de tomate, queijo e arroz", 6290],
  ["Parmegiana de Frango", "Frango crocante, molho de tomate, queijo e arroz", 4690],
  ["Moqueca de Peixe", "Peixe branco, leite de coco, dendê e arroz", 5790],
  ["Arroz de Pato", "Arroz caldoso de pato, laranja e ervas", 5890],
  ["Estrogonofe de Mignon", "Mignon, cogumelos, arroz branco e batata palha", 5190],
  ["Camarão na Moranga", "Camarões cremosos servidos em abóbora assada", 7190],
  ["Cuscuz de Legumes", "Cuscuz marroquino, legumes grelhados e ervas", 3790],
  ["Bife de Chorizo", "Chorizo na brasa, farofa crocante e vinagrete", 6790],
];

const desserts: Array<[string, string, number]> = [
  ["Petit Gâteau", "Bolo de chocolate quente com sorvete de baunilha", 2790],
  ["Pudim de Leite", "Pudim cremoso com caramelo artesanal", 1890],
  ["Tiramisu", "Mascarpone, café, cacau e biscoitos champagne", 2690],
  ["Cheesecake de Frutas Vermelhas", "Base crocante, creme de queijo e calda de frutas", 2790],
  ["Mousse de Chocolate", "Chocolate intenso, creme e crocante de cacau", 2290],
  ["Crème Brûlée", "Creme de baunilha e crosta de açúcar queimado", 2490],
  ["Banoffee", "Banana, doce de leite, chantilly e canela", 2390],
  ["Brownie com Sorvete", "Brownie de chocolate e sorvete artesanal", 2690],
  ["Pavlova Tropical", "Merengue, creme leve e frutas da estação", 2590],
  ["Mil-folhas de Doce de Leite", "Massa folhada, doce de leite e flor de sal", 2490],
  ["Torta de Limão", "Creme cítrico, merengue tostado e massa crocante", 2090],
  ["Bolo de Coco Gelado", "Coco fresco, leite condensado e calda cremosa", 1890],
  ["Cocada Cremosa", "Coco queimado, creme e farofa de castanhas", 1990],
  ["Romeu e Julieta", "Queijo meia cura e goiabada artesanal", 1790],
  ["Sorvete de Baunilha", "Duas bolas de sorvete artesanal de baunilha", 1490],
  ["Sorvete de Chocolate", "Duas bolas de sorvete artesanal de chocolate", 1490],
  ["Sorvete de Pistache", "Duas bolas de sorvete artesanal de pistache", 1890],
  ["Affogato", "Sorvete de baunilha servido com café espresso", 1990],
  ["Frutas da Estação", "Seleção fresca de frutas da estação", 1690],
  ["Maçã Assada", "Maçã caramelizada, canela e creme inglês", 2290],
  ["Bolo de Cenoura", "Bolo macio com ganache de chocolate", 1890],
  ["Crumble de Banana", "Banana assada, farofa doce e sorvete", 2290],
  ["Mousse de Maracujá", "Mousse aerada e calda fresca de maracujá", 1890],
  ["Churros com Doce de Leite", "Churros quentes, açúcar e doce de leite", 2190],
  ["Panna Cotta", "Creme italiano de baunilha e calda de frutas", 2390],
  ["Torta Basca", "Cheesecake queimado com calda de caramelo", 2790],
  ["Suflê de Goiabada", "Suflê leve, goiabada e creme de queijo", 2490],
  ["Cannoli Siciliano", "Massa crocante, ricota doce e pistache", 2390],
  ["Bolo de Chocolate", "Bolo intenso com ganache e morangos", 2290],
  ["Café Gourmand", "Espresso acompanhado de três mini sobremesas", 2890],
];

const drinks: Array<[string, string, number]> = [
  ["Água Mineral sem Gás", "Garrafa de água mineral 500 ml", 690],
  ["Água Mineral com Gás", "Garrafa de água mineral com gás 500 ml", 790],
  ["Água Tônica", "Água tônica premium, lata 350 ml", 990],
  ["Refrigerante Cola", "Refrigerante cola, lata 350 ml", 890],
  ["Refrigerante Cola Zero", "Refrigerante cola sem açúcar, lata 350 ml", 890],
  ["Refrigerante Limão", "Refrigerante sabor limão, lata 350 ml", 890],
  ["Refrigerante Guaraná", "Refrigerante guaraná, lata 350 ml", 890],
  ["Suco de Laranja", "Suco de laranja natural 300 ml", 1290],
  ["Suco de Limão", "Limonada fresca com hortelã 300 ml", 1190],
  ["Suco de Maracujá", "Suco natural de maracujá 300 ml", 1290],
  ["Suco de Abacaxi", "Suco de abacaxi com hortelã 300 ml", 1290],
  ["Chá Gelado", "Chá preto, limão e pêssego 300 ml", 1090],
  ["Café Espresso", "Café especial em dose simples", 690],
  ["Café Espresso Duplo", "Café especial em dose dupla", 890],
  ["Cappuccino", "Espresso, leite vaporizado e canela", 1190],
  ["Cerveja Pilsen", "Long neck 355 ml, leve e refrescante", 1390],
  ["Cerveja IPA", "Long neck 355 ml, cítrica e aromática", 1690],
  ["Cerveja Weiss", "Long neck 500 ml, trigo e especiarias", 1890],
  ["Chopp Claro", "Taça de chopp claro 300 ml", 1290],
  ["Chopp Escuro", "Taça de chopp escuro 300 ml", 1390],
  ["Caipirinha Clássica", "Cachaça, limão, açúcar e gelo", 2290],
  ["Caipirinha de Maracujá", "Cachaça, maracujá, açúcar e gelo", 2490],
  ["Mojito", "Rum, hortelã, limão, açúcar e soda", 2790],
  ["Aperol Spritz", "Aperol, espumante brut e água com gás", 3290],
  ["Negroni", "Gin, vermute rosso e bitter italiano", 3490],
  ["Gin Tônica", "Gin premium, tônica e botânicos", 3690],
  ["Moscow Mule", "Vodca, gengibre, limão e espuma", 3190],
  ["Margarita", "Tequila, licor de laranja, limão e sal", 3290],
  ["Sangria da Casa", "Vinho, frutas frescas e especiarias", 2790],
  ["Limonada Rosa", "Limão, frutas vermelhas e água com gás", 1490],
];

const wines: Array<[string, string, number]> = [
  ["Espumante Brut Casa Valduga", "Brasil · Serra Gaúcha · Taça 150 ml", 2990],
  ["Espumante Moscatel", "Brasil · Serra Gaúcha · Taça 150 ml", 2490],
  ["Prosecco Italiano", "Itália · Veneto · Taça 150 ml", 3490],
  ["Champagne Moët & Chandon", "França · Champagne · Garrafa 750 ml", 69000],
  ["Sauvignon Blanc Andeluna", "Argentina · Mendoza · Taça 150 ml", 2990],
  ["Chardonnay Catena", "Argentina · Mendoza · Taça 150 ml", 3490],
  ["Pinot Grigio Santa Cristina", "Itália · Toscana · Garrafa 750 ml", 18900],
  ["Rosé Whispering Angel", "França · Provence · Garrafa 750 ml", 32900],
  ["Rosé Miolo Seleção", "Brasil · Campanha · Taça 150 ml", 2490],
  ["Pinot Noir Leyda", "Chile · Vale de Leyda · Taça 150 ml", 3190],
  ["Merlot Miolo", "Brasil · Vale dos Vinhedos · Taça 150 ml", 2690],
  ["Malbec Catena", "Argentina · Mendoza · Taça 150 ml", 3690],
  ["Malbec Alta Vista", "Argentina · Mendoza · Garrafa 750 ml", 22900],
  ["Cabernet Sauvignon Montes", "Chile · Colchagua · Taça 150 ml", 3290],
  ["Carmenère Casa Silva", "Chile · Colchagua · Taça 150 ml", 2990],
  ["Tempranillo Ramón Bilbao", "Espanha · Rioja · Garrafa 750 ml", 21900],
  ["Rioja Crianza", "Espanha · Rioja · Taça 150 ml", 3390],
  ["Chianti Classico", "Itália · Toscana · Garrafa 750 ml", 24900],
  ["Brunello di Montalcino", "Itália · Toscana · Garrafa 750 ml", 48900],
  ["Amarone della Valpolicella", "Itália · Veneto · Garrafa 750 ml", 51900],
  ["Bordeaux Réserve", "França · Bordeaux · Garrafa 750 ml", 31900],
  ["Côtes du Rhône", "França · Rhône · Taça 150 ml", 3690],
  ["Porto Tawny 10 Anos", "Portugal · Douro · Taça 90 ml", 3290],
  ["Vinho Verde Alvarinho", "Portugal · Minho · Taça 150 ml", 2790],
  ["Syrah Ventisquero", "Chile · Maipo · Garrafa 750 ml", 19900],
  ["Tannat Garzón", "Uruguai · Maldonado · Taça 150 ml", 3490],
  ["Primitivo Puglia", "Itália · Puglia · Garrafa 750 ml", 23900],
  ["Barolo DOCG", "Itália · Piemonte · Garrafa 750 ml", 57900],
  ["Cabernet Franc Rutini", "Argentina · Mendoza · Garrafa 750 ml", 25900],
  ["Blend Sabor & Mesa", "Brasil · Edição da casa · Taça 150 ml", 2790],
];

function mapCategory(
  category: CatalogSeedItem["category"],
  items: Array<[string, string, number]>,
): CatalogSeedItem[] {
  return items.map(([name, description, priceCents]) => ({ name, description, priceCents, category }));
}

export const catalogSeed: CatalogSeedItem[] = [
  ...mapCategory("entradas", entries),
  ...mapCategory("pratos_principais", mains),
  ...mapCategory("sobremesas", desserts),
  ...mapCategory("bebidas", drinks),
  ...mapCategory("vinhos", wines),
];

export const catalogCategoryLabels: Record<CatalogSeedItem["category"], string> = {
  entradas: "Entradas",
  pratos_principais: "Pratos principais",
  sobremesas: "Sobremesas",
  bebidas: "Bebidas",
  vinhos: "Carta de vinhos",
};
